<h2>MNIST Part 1</h2>
<br>
In this example, we use basic Neural Network to classfing MNIST data.

In [21]:
import pandas as pd
import numpy as np

from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D, BatchNormalization
from keras.optimizers import SGD, Adam
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import LearningRateScheduler, EarlyStopping

np.random.seed(123)

In [3]:
from keras.datasets import mnist

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

<h2>Investigate data format</h2>

In [6]:
x_train[0][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0], dtype=uint8)

In [7]:
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [8]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


<h2>Data transform and data preprocessing</h2>

In [9]:
# since mnist data is 28*28, 0-255 grayscale, scale it to range(0,1)
x_train = x_train.astype('float32')/255.0
x_test = x_test.astype('float32')/255.0

n_train = x_train.shape[0]
n_test = x_test.shape[0]

x_train = x_train.reshape(n_train, 784) # n rows with 784 columns
x_test = x_test.reshape(n_test, 784)

In [10]:
# encoding classes
print(y_train[0])
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
print(y_train[0])

5
[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]


<h2>Model initializing and building</h2>

In [12]:
# model parameters initializing
train_size = 20000

# random sampling from training set
sample_test = np.random.choice(np.arange(n_train), train_size, replace=False) # 60000 choose 20000
x_sample = x_train[sample_test]
y_sample = y_train[sample_test]

# hyperparameters
learning_rate = 0.5
batch_size = 300
epoch_num = 20

In [13]:
model = Sequential()
model.add(Dense(200, activation='relu', input_dim=(784)))
model.add(Dense(100, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [14]:
# optimization method: SGD
model.compile(optimizer=SGD(lr=learning_rate), loss='categorical_crossentropy', metrics=['accuracy'])

In [15]:
model_fit_one = model.fit(x_sample, y_sample, validation_split=0.3, batch_size=batch_size, epochs=epoch_num)

Train on 14000 samples, validate on 6000 samples
Epoch 1/20
14000/14000 [==============================] - 0s - loss: 12.2486 - acc: 0.1558 - val_loss: 14.4391 - val_acc: 0.1042

<h2>Model evaluation</h2>

In [20]:
# model evaluation
result = model.evaluate(x_test, y_test)
print("\n")
print("Loss: ",result[0])
print("Accuracy: ",result[1])

 9536/10000 [===========================>..] - ETA: 0s

Loss:  14.4611550446
Accuracy:  0.1028
